# Tracked drivers for official result summaries
# Set enabled: false to skip a driver

drivers:
  - name: "Joe Zubo"
    iracing_id: 486889
    discord_id: "357172893412491264"
    enabled: true

  - name: "Mike Popp"
    iracing_id: 508009
    discord_id: "700425120719568896"
    enabled: true

  - name: "Tom LeBaron"
    iracing_id: 935585
    discord_id: "570322513029103636"
    enabled: true
